### ISSUE TITLE
Hebrew treebank

### ISSUE THREAD

**Issue by natalink** [ufal/lindat-corpora-conversions#2]
I have two issues with the Hebrew corpus:
1. How to deal with right-to-left writing system? Question to Michal Kren how they did it for a parallel corpus
2. How shall I process the cases like 2-3 in the following:
   1       שוטר    _       NOUN    NOUN    Gender=Masc|Number=Sing 4       nsubj   _       _
   2-3     וחייל   _       _       _       _       _       _       _       _
   2       ו       _       CONJ    CONJ    _       1       cc      _       _
   3       חייל    _       NOUN    NOUN    Gender=Masc|Number=Sing 1       conj    _       _
   4       אחזו    _       VERB    VERB    Gender=Fem,Masc|Number=Plur|Person=3|Tense=Past 0       root
   Shall I completely delete this line?

**Comment by dan-zeman** [comment]
1. Ideally, the nodes in the tree should be reordered so that they appear right-to-left on the screen. But even if this is not possible, the text inside a node (the form and the lemma) must appear right-to-left. However, this latter part should not be a problem because the client operating system (and/or the browser) should be able to render it correctly.

**Comment by dan-zeman** [comment]
As for 2: The "interval node ids" such as "2-3" represent fused words that appear as one token on the surface but they are split to "syntactic words" for the purpose of the UD annotation. If you just want to display the tree, you can ignore the interval lines (they should always be followed by lines with the individual nodes within the interval). But if you convert the data to another format and the data should later be recoverable, you have to keep the information somewhere.
